package httpapi

// swaggerRoutes ? contracts/swagger.json ????????????????
var swaggerRoutes = []Route{
	{Method: "POST", Path: "/Favor/Del", Module: "Favor", Operation: "删除收藏"},
	{Method: "POST", Path: "/Favor/GetFavInfo", Module: "Favor", Operation: "获取搜藏信息"},
	{Method: "POST", Path: "/Favor/GetFavItem", Module: "Favor", Operation: "读取收藏内容"},
	{Method: "POST", Path: "/Favor/Sync", Module: "Favor", Operation: "同步收藏"},
	{Method: "POST", Path: "/Finder/UserPrepare", Module: "Finder", Operation: "用户中心"},
	{Method: "POST", Path: "/Friend/Blacklist", Module: "Friend", Operation: "添加/移除黑名单"},
	{Method: "POST", Path: "/Friend/Delete", Module: "Friend", Operation: "删除好友"},
	{Method: "POST", Path: "/Friend/GetContractDetail", Module: "Friend", Operation: "获取通讯录好友详情"},
	{Method: "POST", Path: "/Friend/GetContractList", Module: "Friend", Operation: "获取通讯录好友"},
	{Method: "POST", Path: "/Friend/GetFriendRelation", Module: "Friend", Operation: "获取好友关系状态"},
	{Method: "POST", Path: "/Friend/GetMFriend", Module: "Friend", Operation: "获取手机通讯录"},
	{Method: "POST", Path: "/Friend/PassVerify", Module: "Friend", Operation: "通过好友请求"},
	{Method: "POST", Path: "/Friend/Search", Module: "Friend", Operation: "搜索联系人"},
	{Method: "POST", Path: "/Friend/SendRequest", Module: "Friend", Operation: "添加联系人"},
	{Method: "POST", Path: "/Friend/SetRemarks", Module: "Friend", Operation: "设置好友备注"},
	{Method: "POST", Path: "/Friend/Upload", Module: "Friend", Operation: "上传通讯录"},
	{Method: "POST", Path: "/FriendCircle/Comment", Module: "FriendCircle", Operation: "朋友圈点赞/评论"},
	{Method: "POST", Path: "/FriendCircle/GetDetail", Module: "FriendCircle", Operation: "获取特定人朋友圈"},
	{Method: "POST", Path: "/FriendCircle/GetIdDetail", Module: "FriendCircle", Operation: "获取特定ID详情内容"},
	{Method: "POST", Path: "/FriendCircle/GetList", Module: "FriendCircle", Operation: "朋友圈首页列表"},
	{Method: "POST", Path: "/FriendCircle/Messages", Module: "FriendCircle", Operation: "发布朋友圈"},
	{Method: "POST", Path: "/FriendCircle/MmSnsSync", Module: "FriendCircle", Operation: "朋友圈同步"},
	{Method: "POST", Path: "/FriendCircle/Operation", Module: "FriendCircle", Operation: "朋友圈操作"},
	{Method: "POST", Path: "/FriendCircle/PrivacySettings", Module: "FriendCircle", Operation: "朋友圈权限设置"},
	{Method: "POST", Path: "/FriendCircle/Upload", Module: "FriendCircle", Operation: "朋友圈上传"},
	{Method: "POST", Path: "/Group/AddChatRoomMember", Module: "Group", Operation: "增加群成员(40人以内)"},
	{Method: "POST", Path: "/Group/ConsentToJoin", Module: "Group", Operation: "同意进入群聊"},
	{Method: "POST", Path: "/Group/CreateChatRoom", Module: "Group", Operation: "创建群聊"},
	{Method: "POST", Path: "/Group/DelChatRoomMember", Module: "Group", Operation: "删除群成员"},
	{Method: "POST", Path: "/Group/FacingCreateChatRoom", Module: "Group", Operation: "面对面创建群聊"},
	{Method: "POST", Path: "/Group/GetChatRoomInfo", Module: "Group", Operation: "获取群详情(不带公告内容)"},
	{Method: "POST", Path: "/Group/GetChatRoomInfoDetail", Module: "Group", Operation: "获取群信息(带公告内容)"},
	{Method: "POST", Path: "/Group/GetChatRoomMemberDetail", Module: "Group", Operation: "获取群成员详情"},
	{Method: "POST", Path: "/Group/GetQRCode", Module: "Group", Operation: "获取群二维码"},
	{Method: "POST", Path: "/Group/InviteChatRoomMember", Module: "Group", Operation: "邀请群成员(40人以上)"},
	{Method: "POST", Path: "/Group/MoveContractList", Module: "Group", Operation: "保存到通讯录"},
	{Method: "POST", Path: "/Group/OperateChatRoomAdmin", Module: "Group", Operation: "群管理操作(添加、删除、转让)"},
	{Method: "POST", Path: "/Group/Quit", Module: "Group", Operation: "退出群聊"},
	{Method: "POST", Path: "/Group/ScanIntoGroup", Module: "Group", Operation: "扫码进群"},
	{Method: "POST", Path: "/Group/ScanIntoGroupEnterprise", Module: "Group", Operation: "扫码进群(企业群)"},
	{Method: "POST", Path: "/Group/SetChatRoomAnnouncement", Module: "Group", Operation: "设置群公告"},
	{Method: "POST", Path: "/Group/SetChatRoomName", Module: "Group", Operation: "设置群名称"},
	{Method: "POST", Path: "/Group/SetChatRoomRemarks", Module: "Group", Operation: "设置群备注(仅自己可见)"},
	{Method: "POST", Path: "/Label/Add", Module: "Label", Operation: "添加标签"},
	{Method: "POST", Path: "/Label/Delete", Module: "Label", Operation: "删除标签"},
	{Method: "POST", Path: "/Label/GetList", Module: "Label", Operation: "获取标签列表"},
	{Method: "POST", Path: "/Label/UpdateList", Module: "Label", Operation: "更新标签列表"},
	{Method: "POST", Path: "/Label/UpdateName", Module: "Label", Operation: "修改标签"},
	{Method: "POST", Path: "/Login/62data", Module: "Login", Operation: "62登陆(账号或密码) - iphone == 8.0.59"},
	{Method: "POST", Path: "/Login/A16Data", Module: "Login", Operation: "A16登陆(账号或密码) - android == 8.0.58"},
	{Method: "POST", Path: "/Login/A16Data1", Module: "Login", Operation: "A16登陆(账号或密码) - android == 新版本云函数"},
	{Method: "POST", Path: "/Login/Awaken", Module: "Login", Operation: "唤醒登陆(只限扫码登录)"},
	{Method: "POST", Path: "/Login/CheckQR", Module: "Login", Operation: "检测二维码"},
	{Method: "POST", Path: "/Login/ExtDeviceLoginConfirmGet", Module: "Login", Operation: "新设备扫码登录"},
	{Method: "POST", Path: "/Login/ExtDeviceLoginConfirmOk", Module: "Login", Operation: "新设备扫码确认登录"},
	{Method: "POST", Path: "/Login/Get62Data", Module: "Login", Operation: "获取62数据"},
	{Method: "POST", Path: "/Login/GetA16Data", Module: "Login", Operation: "获取A16数据"},
	{Method: "POST", Path: "/Login/GetCacheInfo", Module: "Login", Operation: "获取登陆缓存信息"},
	{Method: "POST", Path: "/Login/GetQR", Module: "Login", Operation: "获取二维码(iPad) - 8.0.59"},
	{Method: "POST", Path: "/Login/GetQRCar", Module: "Login", Operation: "获取二维码(Car) - 1.0.9"},
	{Method: "POST", Path: "/Login/GetQRMac", Module: "Login", Operation: "获取二维码(Mac) - 3.8.8"},
	{Method: "POST", Path: "/Login/GetQRPad", Module: "Login", Operation: "获取二维码(安卓Pad) - 8.0.58"},
	{Method: "POST", Path: "/Login/GetQRPad1", Module: "Login", Operation: "获取二维码(安卓Pad) - 新版云函数"},
	{Method: "POST", Path: "/Login/GetQRPadx", Module: "Login", Operation: "获取二维码(安卓Pad-绕过验证码)"},
	{Method: "POST", Path: "/Login/GetQRWin", Module: "Login", Operation: "获取二维码(Windows) - 4.0.3.43"},
	{Method: "POST", Path: "/Login/GetQRWinUnified", Module: "Login", Operation: "获取二维码(Win-PC版 - 支持ppmt)"},
	{Method: "POST", Path: "/Login/GetQRWinUwp", Module: "Login", Operation: "获取二维码(WindowsUwp-绕过验证码)"},
	{Method: "POST", Path: "/Login/GetQRx", Module: "Login", Operation: "获取二维码(iPad-绕过验证码)"},
	{Method: "POST", Path: "/Login/HeartBeat", Module: "Login", Operation: "心跳包"},
	{Method: "POST", Path: "/Login/HeartBeatLong", Module: "Login", Operation: "长连接心跳包"},
	{Method: "POST", Path: "/Login/LogOut", Module: "Login", Operation: "退出登录"},
	{Method: "POST", Path: "/Login/Newinit", Module: "Login", Operation: "初始化"},
	{Method: "POST", Path: "/Login/TwiceAutoAuth", Module: "Login", Operation: "二次登陆"},
	{Method: "POST", Path: "/Msg/Revoke", Module: "Msg", Operation: "撤回消息"},
	{Method: "POST", Path: "/Msg/SendApp", Module: "Msg", Operation: "发送App消息"},
	{Method: "POST", Path: "/Msg/SendCDNFile", Module: "Msg", Operation: "发送文件(转发,并非上传)"},
	{Method: "POST", Path: "/Msg/SendCDNImg", Module: "Msg", Operation: "发送Cdn图片(转发图片)"},
	{Method: "POST", Path: "/Msg/SendCDNVideo", Module: "Msg", Operation: "发送Cdn视频(转发视频)"},
	{Method: "POST", Path: "/Msg/SendEmoji", Module: "Msg", Operation: "发送Emoji"},
	{Method: "POST", Path: "/Msg/SendTxt", Module: "Msg", Operation: "发送文本消息"},
	{Method: "POST", Path: "/Msg/SendVideo", Module: "Msg", Operation: "发送视频"},
	{Method: "POST", Path: "/Msg/SendVoice", Module: "Msg", Operation: "发送语音"},
	{Method: "POST", Path: "/Msg/ShareCard", Module: "Msg", Operation: "分享名片"},
	{Method: "POST", Path: "/Msg/ShareLink", Module: "Msg", Operation: "发送分享链接消息"},
	{Method: "POST", Path: "/Msg/ShareLocation", Module: "Msg", Operation: "分享位置"},
	{Method: "POST", Path: "/Msg/ShareVideo", Module: "Msg", Operation: "发送分享视频消息"},
	{Method: "POST", Path: "/Msg/Sync", Module: "Msg", Operation: "同步消息"},
	{Method: "POST", Path: "/Msg/UploadImg", Module: "Msg", Operation: "发送图片"},
	{Method: "POST", Path: "/OfficialAccounts/Follow", Module: "OfficialAccounts", Operation: "关注"},
	{Method: "POST", Path: "/OfficialAccounts/GetAppMsgExt", Module: "OfficialAccounts", Operation: "阅读文章,返回 分享、看一看、阅读数据"},
	{Method: "POST", Path: "/OfficialAccounts/GetAppMsgExtLike", Module: "OfficialAccounts", Operation: "点赞文章,返回 分享、看一看、阅读数据"},
	{Method: "POST", Path: "/OfficialAccounts/JSAPIPreVerify", Module: "OfficialAccounts", Operation: "JSAPIPreVerify"},
	{Method: "POST", Path: "/OfficialAccounts/MpGetA8Key", Module: "OfficialAccounts", Operation: "MpGetA8Key(获取文章key和uin)"},
	{Method: "POST", Path: "/OfficialAccounts/OauthAuthorize", Module: "OfficialAccounts", Operation: "OauthAuthorize"},
	{Method: "POST", Path: "/OfficialAccounts/Quit", Module: "OfficialAccounts", Operation: "取消关注"},
	{Method: "POST", Path: "/QWContact/QWAddContact", Module: "QWContact", Operation: "添加企业好友"},
	{Method: "POST", Path: "/QWContact/QWApplyAddContact", Module: "QWContact", Operation: "主动添加企业好友"},
	{Method: "POST", Path: "/QWContact/SearchQWContact", Module: "QWContact", Operation: "搜索企业好友"},
	{Method: "POST", Path: "/SayHello/Modelv1", Module: "SayHello", Operation: "模式1-扫码"},
	{Method: "POST", Path: "/SayHello/Modelv2", Module: "SayHello", Operation: "模式2-一键打招呼"},
	{Method: "POST", Path: "/SayHello/Modelv3", Module: "SayHello", Operation: "模式3-v3v4通道打招呼"},
	{Method: "POST", Path: "/Tools/CdnDownloadImage", Module: "Tools", Operation: "CDN高清图片下载"},
	{Method: "POST", Path: "/Tools/DownloadFile", Module: "Tools", Operation: "文件下载"},
	{Method: "POST", Path: "/Tools/DownloadImg", Module: "Tools", Operation: "高清图片下载"},
	{Method: "POST", Path: "/Tools/DownloadVideo", Module: "Tools", Operation: "视频下载"},
	{Method: "POST", Path: "/Tools/DownloadVoice", Module: "Tools", Operation: "语音下载"},
	{Method: "GET", Path: "/Tools/GeneratePayQCode", Module: "Tools", Operation: "生成支付二维码"},
	{Method: "POST", Path: "/Tools/GetA8Key", Module: "Tools", Operation: "GetA8Key"},
	{Method: "POST", Path: "/Tools/GetBandCardList", Module: "Tools", Operation: "获取余额以及银行卡信息"},
	{Method: "POST", Path: "/Tools/GetBoundHardDevices", Module: "Tools", Operation: "GetBoundHardDevices"},
	{Method: "POST", Path: "/Tools/GetCdnDns", Module: "Tools", Operation: "获取CDN服务器dns信息"},
	{Method: "POST", Path: "/Tools/ThirdAppGrant", Module: "Tools", Operation: "第三方APP授权"},
	{Method: "POST", Path: "/Tools/UpdateStep", Module: "Tools", Operation: "修改微信步数"},
	{Method: "POST", Path: "/Tools/setproxy", Module: "Tools", Operation: "设置/删除代理IP"},
	{Method: "POST", Path: "/User/BindQQ", Module: "User", Operation: "绑定QQ"},
	{Method: "POST", Path: "/User/BindingEmail", Module: "User", Operation: "绑定邮箱"},
	{Method: "POST", Path: "/User/BindingMobile", Module: "User", Operation: "换绑手机号"},
	{Method: "POST", Path: "/User/DelSafetyInfo", Module: "User", Operation: "删除登录设备"},
	{Method: "POST", Path: "/User/GetContractProfile", Module: "User", Operation: "取个人信息"},
	{Method: "POST", Path: "/User/GetQRCode", Module: "User", Operation: "取个人二维码"},
	{Method: "POST", Path: "/User/GetSafetyInfo", Module: "User", Operation: "登录设备管理"},
	{Method: "POST", Path: "/User/PrivacySettings", Module: "User", Operation: "隐私设置"},
	{Method: "POST", Path: "/User/ReportMotion", Module: "User", Operation: "ReportMotion"},
	{Method: "POST", Path: "/User/SendVerifyMobile", Module: "User", Operation: "发送手机验证码"},
	{Method: "POST", Path: "/User/SetAlisa", Module: "User", Operation: "设置微信号"},
	{Method: "POST", Path: "/User/SetPasswd", Module: "User", Operation: "修改密码"},
	{Method: "POST", Path: "/User/UpdateProfile", Module: "User", Operation: "修改个人信息"},
	{Method: "POST", Path: "/User/UploadHeadImage", Module: "User", Operation: "修改头像"},
	{Method: "POST", Path: "/User/VerifyPasswd", Module: "User", Operation: "验证密码"},
	{Method: "POST", Path: "/Wxapp/AddAvatar", Module: "Wxapp", Operation: "添加小程序头像昵称身份"},
	{Method: "POST", Path: "/Wxapp/AddMobile", Module: "Wxapp", Operation: "小程序绑定增加手机号"},
	{Method: "POST", Path: "/Wxapp/AddWxAppRecord", Module: "Wxapp", Operation: "开授权-添加小程序历史记录"},
	{Method: "POST", Path: "/Wxapp/CloudCallFunction", Module: "Wxapp", Operation: "小程序云函数"},
	{Method: "POST", Path: "/Wxapp/DelMobile", Module: "Wxapp", Operation: "小程序删除手机号"},
	{Method: "POST", Path: "/Wxapp/GetRandomAvatar", Module: "Wxapp", Operation: "获取随机小程序头像昵称身份"},
	{Method: "POST", Path: "/Wxapp/GetUserOpenId", Module: "Wxapp", Operation: "获取用户openid"},
	{Method: "POST", Path: "/Wxapp/JSGetSessionid", Module: "Wxapp", Operation: "获取小程序支付sessionid"},
	{Method: "POST", Path: "/Wxapp/JSGetSessionidQRcode", Module: "Wxapp", Operation: "获取小程序支付二维码"},
	{Method: "POST", Path: "/Wxapp/JSLogin", Module: "Wxapp", Operation: "授权小程序(返回授权后的code)"},
	{Method: "POST", Path: "/Wxapp/JSOperateWxData", Module: "Wxapp", Operation: "小程序操作"},
	{Method: "POST", Path: "/Wxapp/QrcodeAuthLogin", Module: "Wxapp", Operation: "扫码授权登录app或网页"},
	{Method: "POST", Path: "/Wxapp/UploadAvatarImg", Module: "Wxapp", Operation: "上传小程序身份头像"},
}

func AllRoutes() []Route {
	out := make([]Route, len(swaggerRoutes))
	copy(out, swaggerRoutes)
	return out
}

func HasRoute(method, path string) bool {
	for _, route := range swaggerRoutes {
		if route.Method == method && route.Path == path {
			return true
		}
	}
	return false
}
